services:
  pgsql-ticket:
    image: postgres:17.6
    ports:
      - "9876:5432"
    environment:
      - POSTGRES_PASSWORD=pgsql-ticket-password
      - POSTGRES_USER=pgsql-ticket-master
    
    networks:
      - backend

    volumes:
      #scripts de cria√ßao dos bancos de dados
      - ./01-create-database-user.sql:/docker-entrypoint-initdb.d/01-create-database-users.sql
      - ./02-create-database-sales.sql:/docker-entrypoint-initdb.d/02-create-database-sales.sql
      - ./03-create-database-notifications.sql:/docker-entrypoint-initdb.d/03-create-database-notifications.sql

      #mapear a pasta de dados para o host - preservar os dados
      - ./pg_data:/var/lib/postgresql/data
    
  pgadmin:
    image: dpage/pgadmin4:8.4
    ports: 
      - "8123:80"
      - "8443:443"
    environment:
      - PGADMIN_DEFAULT_EMAIL=web@ufop.edu.br
      - PGADMIN_DEFAULT_PASSWORD=123456
    networks:
      - backend

networks:
  frontend:
  backend: